### ISSUE TITLE
Is there any configuration that needs to be done?

### ISSUE THREAD

**Issue by Meister1867** [CarpeDatumInc/vscode-tm1#1]
I think I'm running into issues when I use the CarpeDatum theme.  It doesn't colorize the text.  However, if I use Dark+, I get colorization of keywords.

I've used my own colorizer for TM1/PA in the past, but judging from what I see in the preview of the extension this appears to be much more advanced than just adding color to the keywords.

**Comment by SGarno** [comment]
Actually the theme has been updated on GitHub, but has not been pushed to VSCode extensions.   Try copying down the CDCDark.theme.json from this repository into your directory and let me know if this works.    You may also want to get the TM1.Rule.Snippets.json file.   I just pushed a tweak on the rules that have spaces in the dimension names  (i.e. !Account Measures) now highlights properly.
