### ISSUE TITLE
If( SomeFunc();)

### ISSUE THREAD

**Issue by marfrit** [CarpeDatumInc/vscode-tm1#4]
Whenever I type a nested function call, the semicolon will be added. So If( CubeExi&lt;tab>); will be replaced to If( CubeExists(sCubeName); ) - is there a way to fix that?

**Comment by SGarno** [comment]
Yes, we are looking to remove that as well in the next update.    All you need to do is go into the snippets file and remove them.    

C:\Users\{user}\.vscode\extensions\carpedatum.tm1-helper-1.0.0\snippets\tm1.process.snippets.json
